import type { MatchResult } from './types';

export const mockResults: MatchResult[] = [
  {
    id: '1',
    name: 'Alex Rivera',
    role: 'Founding Engineer',
    company: 'Arcane Labs',
    mutualContext: 'Met 3× in last 60 days',
    strengthLabel: 'Strong tie',
    relevanceLabel: 'Hiring: Founding Eng',
    pathString: 'You → Sam → Alex',
    trustMeter: {
      strength: 'High',
      recency: 'Last met 2 weeks ago',
      confidence: 'High',
    },
    provenanceLabel: 'Source: Calendar + Email (verified)',
    askSummary: 'Intro to discuss founding engineer role',
  },
  {
    id: '2',
    name: 'Priya Chakraborty',
    role: 'GP, Seed Stage',
    company: 'Northlight Ventures',
    mutualContext: 'Met 1× in last 90 days',
    strengthLabel: 'Moderate tie',
    relevanceLabel: 'Fundraising: Pre-seed',
    pathString: 'You → Jordan → Priya',
    trustMeter: {
      strength: 'Med',
      recency: 'Last met 6 weeks ago',
      confidence: 'Med',
    },
    provenanceLabel: 'Source: Calendar (verified)',
    askSummary: 'Intro to explore seed investment fit',
  },
  {
    id: '3',
    name: 'Marcus Chen',
    role: 'Head of Product',
    company: 'Lattice',
    mutualContext: 'Met 5× in last 30 days',
    strengthLabel: 'Strong tie',
    relevanceLabel: 'Advisor: Product strategy',
    pathString: 'You → Marcus',
    trustMeter: {
      strength: 'High',
      recency: 'Last met 3 days ago',
      confidence: 'High',
    },
    provenanceLabel: 'Source: Calendar + Email (verified)',
    askSummary: 'Intro to discuss product advisory role',
  },
  {
    id: '4',
    name: 'Elena Vasquez',
    role: 'Design Lead',
    company: 'Figma',
    mutualContext: 'Met 2× in last 120 days',
    strengthLabel: 'Weak tie',
    relevanceLabel: 'Hiring: Senior Designer',
    pathString: 'You → Nia → Dev → Elena',
    trustMeter: {
      strength: 'Low',
      recency: 'Last met 4 months ago',
      confidence: 'Low',
    },
    provenanceLabel: 'Source: CRM (imported)',
    askSummary: 'Intro to discuss senior design opening',
  },
];
